import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={[
          inter.className,
        ]}
      >
        <div className="w-full max-w-96 mx-auto h-screen bg-gray-100">{children}</div>
      </body>
    </html>
  );
}
